version: 2
jobs:
  build:
    machine: true
    steps:
      - checkout

      - run:
          name: build_publish_image
          command: |
            export DH_USER=`echo ${DOCKER_HUB_USER} | base64 --decode`
            export DH_PASS=`echo ${DOCKER_HUB_PASS} | base64 --decode`
            docker login -u $DH_USER --password-stdin $DH_PASS
            docker build -t aniskhan001/napi:$CIRCLE_BRANCH .
            docker push aniskhan001/napi:$CIRCLE_BRANCH

  test:
    docker:
      - image: aniskhan001/napi:$CIRCLE_BRANCH
      - image: mongo:4

    working_directory: ~/napi-ci

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: api-integration-test
          command: mocha
