version: 2
jobs:
  build:
    machine: true
    branches:
      ignore:
        - dependabot/.*
        - /feature-.*/
    steps:
      - checkout

      - run:
          name: build_publish_image
          command: |
            export DH_USER=`echo ${DOCKER_HUB_USER} | base64 -d`
            echo ${DOCKER_HUB_PASS} | base64 -d | docker login -u $DH_USER --password-stdin
            docker build -t aniskhan001/napi:$CIRCLE_BRANCH .
            docker push aniskhan001/napi:$CIRCLE_BRANCH

  test:
    docker:
      - image: circleci/node:10
      - image: circleci/mongo:4

    environment:
      - NODE_ENV: development

    working_directory: ~/napi-ci

    steps:
      - checkout

      # Download and cache dependencies
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          # fallback to using the latest cache if no exact match is found
          - v1-dependencies-

      - run:
          name: install-dependencies
          command: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run:
          name: api-integration-test
          command: npm test

      - run:
          name: generate-coverage
          command: |
            export COVERALLS_SERVICE_NAME=circleci
            export COVERALLS_REPO_TOKEN=${COVERALLS_REPO_TOKEN}
            npm run cover

workflows:
  version: 2
  test_and_build:
    jobs:
      - test
      - build:
          requires:
            - test
