apiVersion: v1
kind: Service
metadata:
  namespace: napi
  name: mongo
  labels:
    app: mongo
spec:
  ports:
    - port: 27017
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: mongo
