---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: napi
  labels:
    app: napi
  annotations:
    flux.weave.works/automated: 'true'
spec:
  replicas: 1
  selector:
    matchLabels:
      app: napi
  template:
    metadata:
      labels:
        app: napi
    spec:
      containers:
      - name: napi
        image: aniskhan001/napi:master
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
        resources:
          requests:
            memory: "50Mi"
            cpu: "100m"
          limits:
            memory: "500Mi"
            cpu: "1"
