---
apiVersion: apps/v1beta2
kind: Deployment
metadata:
  namespace: napi
  name: napi
  labels:
    app: napi
  annotations:
    flux.weave.works/automated: 'true'
    flux.weave.works/tag.napi: glob:main
spec:
  replicas: 1
  selector:
    matchLabels:
      app: napi
  template:
    metadata:
      labels:
        app: napi
    spec:
      containers:
      - name: napi
        image: aniskhan001/napi:main
        imagePullPolicy: Always
        ports:
        - name: http
          containerPort: 3000
          protocol: TCP
