apiVersion: v1
kind: Service
metadata:
  namespace: napi
  name: napi
  labels:
    app: napi
spec:
  ports:
    - port: 3000
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: napi
